### ISSUE TITLE
Submission gateway timeout

### ISSUE THREAD

**Issue by dannytaylor** [leafo/streak.club#54]
When clicking the submit button on a submission page I get a 504 timeout. The submit and upload buttons then get greyed out and the page does not redirect to the streak page. The submission **does** get added to the streak, but any uploads attached to the submission do not save. Issue occurring for me on desktop Chrome and Firefox and mobile Chrome. 

From the [Daily Art discussion sounds like it started happening around 3 weeks ago](https://streak.club/t/26/welcome-2019), at least since Jan 13th. I skimmed through the commits from around then, but not sure what changes would have triggered this. Don't think there's anything interesting in it but here's a screenshot of the POST request that times out.

![1](https://user-images.githubusercontent.com/6579126/52183847-f2124b00-27c0-11e9-9950-b801430dd9fb.png)

I also noticed that the Daily Art streak doesn't have any "Longest Active Streaks" on the leaderboard while some of the music streaks do, not sure if this is related.

**Comment by leafo** [comment]
I'm going to close this because I think the issue has been resolved. It was related to something changing about the dns resolver on our host. Tell me if you spot any issues.

Also longest active streaks is there, tell me if you're not seeing it. (I didn't make any changes to that part of the site afair so the bug may reappear)
